config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

   root 'welcome#index'
   resources "entries"
   resources "websites"
   resources :comments, only: [:create]

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :entry
end

app/models/entry.rb
class Entry < ActiveRecord::Base
	has_many :comments
  has_attached_file :image, styles: { small: "64x64", med: "100x100", large: "200x200" }
  validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
end

app/models/website.rb
class Website < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def index
  		@comments = Comment.all
	 end
	 def show
  		@comment = Comment.find(params["id"])
	 end
    def create
        @comment = Comment.new params[:comment].permit(:entry_id, :contents, :nick)
        
        if @comment.save
          flash[:notice] = "Added comment"
        else
          flash[:alert]  = "Couldn't create comment: #{@comment.errors.full_messages.to_sentence}" 
        end
        
        redirect_to entry_path(@comment.entry)
    end
    def destroy
	 	@comment = Comment.find(params["id"])
	 	@comment.destroy
	 	redirect_to comments_url notice: "Comment was succesfully destroyed"
	 end	
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  def index
    @entries = Entry.where(["date <= ?" , Date.today])
  end
  def show
    @entry = Entry.find(params["id"])
  end
  def new
    @entry= Entry.new
  end
  def create
    entry_params = params["entry"].permit("title","image","contents")
    entry = Entry.create(entry_params)
    redirect_to(entry_path(entry))
  end
  def edit
    @entry = Entry.find(params["id"])
  end
  def update
    entry_params = params["entry"].permit("title", "date" , "image", "youtube_url" , "youtube_embed" ,"contents")
    entry = Entry.find(params["id"])
    entry.update_attributes(entry_params)
    redirect_to(entry_path(entry))
  end
  def destroy
    @entry = Entry.find(params["id"])
    @entry.destroy
    redirect_to entries_url notice: "Entry was succesfully destroyed"
  end
  def date
    time = Time.new

    values = time.to_a
    puts Time.utc(*values)
  end
  end

app/controllers/websites_controller.rb
class WebsitesController < ApplicationController
	def index
  		@websites = Website.all
	 end
	 def show
  		@website = Website.find(params["id"])
	 end
	 def new
	 	@website= Website.new(url: "http://", title: "Witryna ")
	 end
	 def create
  		website_params = params["website"].permit("title", "url")
  		website = Website.create(website_params)
  		redirect_to(website_path(website))
	 end
	 def edit
  		@website = Website.find(params["id"])
	 end
	 def update
  		website_params = params["website"].permit("title","url")
  		website = Website.find(params["id"])
  		website.update(website_params)
  		redirect_to(website_path(website))
	 end
	 def destroy
	 	@website = Website.find(params["id"])
	 	@website.destroy
	 	redirect_to websites_url notice: "Website was succesfully destroyed"
	 end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@entry= Entry.new
  	@entries = Entry.all
    @website= Website.new
    @websites= Website.all

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
  def youtube_embed(youtube_url)
    if youtube_url[/youtu\.be\/([^\?]*)/]
      youtube_id = $1
    else
      # Regex from # http://stackoverflow.com/questions/3452546/javascript-regex-how-to-get-youtube-video-id-from-url/4811367#4811367
      youtube_url[/^.*((v\/)|(embed\/)|(watch\?))\??v?=?([^\&\?]*).*/]
      youtube_id = $5
    end

    raw %Q{<iframe title="YouTube video player" width="320" height="240" src="http://www.youtube.com/embed/#{ youtube_id }" frameborder="0" allowfullscreen></iframe>}
  end
end

app/helpers/websites_helper.rb
module WebsitesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/index.html.erb
<!doctype html>
<html>
  <head>
    <title>My Little Webapp: Coding Is Magic</title>
    <meta charset="UTF-8" />
    <link rel="stylesheet" href="https://rawgithub.com/krzysztofbialek/Rails-Girls-Warsaw-App/master/style.css" />
  </head>
  <body>
  	<div>
  <h1>My favourite websites</h1>
    <ul>
    </ul>
  </div>
  <img src="http://railsgirls.com/images/rg-warsaw.png" />
  </body>
         <% for entry in @entries %>
  <h2><%= link_to(entry.title, entry_path(entry)) %></h2>
  <p><%= entry.date %></p>
  <p><%= entry.contents %></p>
  <p><%= link_to "Delete", entry_path(entry), method: :delete %></p>
    
<% end %>
<%= link_to("New entry", new_entry_path) %>
</html>

app/views/comments/new.html.erb
<!doctype html>
<html>
  <head>
    <title>My Little Webapp: Coding Is Magic</title>
    <meta charset="UTF-8" />
    <link rel="stylesheet" href="https://rawgithub.com/krzysztofbialek/Rails-Girls-Warsaw-App/master/style.css" />
  </head>
  <body>
  	<img src="http://railsgirls.com/images/rg-warsaw.png" />
      <%= form_for(Entry.new) do |form| %>
      <p><%= form.label("title") %></p>
      <p><%= form.text_field("title") %></p>
      <p><%= form.label("contents") %></p>
      <p><%= form.text_area("contents") %></p>
      <p><%= form.submit %></p>
<% end %>
<p><%= link_to("Back to all entries", entries_path) %></p>
  </body>
</html>

app/views/comments/show.html.erb
<!doctype html>
<html>
  <head>
    <title>My Little Webapp: Coding Is Magic</title>
    <meta charset="UTF-8" />
    <link rel="stylesheet" href="https://rawgithub.com/krzysztofbialek/Rails-Girls-Warsaw-App/master/style.css" />
  </head>
  <body>
  	<img src="http://railsgirls.com/images/rg-warsaw.png" />
  	<div>
  <h1>My favourite websites</h1>
  <h2><%= @entry.title %></h2>
  <p><%= @entry.date %></p>
  <p><%= @entry.contents %></p>
  <p><%= link_to("Back to all entries", entries_path) %></p>
  <p><%= link_to("Edit this entry", edit_entry_path(@entry)) %></p>
  <p><%= link_to("Delete this entry", entry_path(@entry)) %></p>

  </div>
  <div>
  
  <%= form_for Comment.new do |f| %>
    <%= f.hidden_field :entry_id, value: @entry.id %>
    <p><%= f.label("entry_id") %></p>
    <p><%= f.label("nick") %></p>
    <p><%= f.text_field("nick") %></p>
    <p><%= f.label("contents") %></p>
    <p><%= f.text_area("contents") %></p>
    <p><%= f.submit %></p>
<% end %>
   <% for comment in @entry.comments %>
    <h3><%= comment.nick %></h3>
  <p><%= comment.contents %></p>
  <p><%= link_to("Delete this comment", comments_path(@comment)) %></p>
  <%end%>
  </div>
  
  </body>
</html>

app/views/entries/_form.html.erb
<%= form_for @entry, html: { multipart: true } do |form| %>
  <p><%= form.file_field :image %></p>
  <p><%= form.label("title") %></p>
  <p><%= form.text_field("youtube_url") %></p>
  <p><%= form.text_field("title") %></p>
  <p><%= form.label("date") %></p>
  <p><%= form.date_field("date") %></p>
  <p><%= form.label("contents") %></p>
  <p><%= form.text_area("contents") %></p>
  <p><%= form.submit %></p>
<% end %>

app/views/entries/edit.html.erb
<!doctype html>
<html>
  <head>
    <title>My Little Webapp: Coding Is Magic</title>
    <meta charset="UTF-8" />
    <link rel="stylesheet" href="https://rawgithub.com/krzysztofbialek/Rails-Girls-Warsaw-App/master/style.css" />
  </head>
  <body>
  	<img src="http://railsgirls.com/images/rg-warsaw.png" />
   <%= form_for(@entry) do |form| %>
  <p><%= form.label("title") %></p>
  <p><%= form.text_field("title") %></p>
  <p><%= form.label("contents") %></p>
  <p><%= form.text_area("contents") %></p>
  <p><%= form.submit %></p>
<% end %>
<p><%= link_to("Back to this entry", entry_path(@entry)) %></p>
<p><%= link_to("Back to all entries", entries_path) %></p>
  </body>
</html>

app/views/entries/index.html.erb
<!doctype html>
<html>
  <head>
    <title>My Little Webapp: Coding Is Magic</title>
    <meta charset="UTF-8" />
    <link rel="stylesheet" href="https://rawgithub.com/krzysztofbialek/Rails-Girls-Warsaw-App/master/style.css" />
  </head>
  <body>
  	<div>
  <h1>My favourite websites</h1>
    <ul>
    </ul>
  </div>
  <img src="http://railsgirls.com/images/rg-warsaw.png" />
  </body>
         <% for entry in @entries %>
  <h2><%= link_to(entry.title, entry_path(entry)) %></h2>
  <p><%= entry.date %></p>
  <% if entry.youtube_url %>
  <%= youtube_embed entry.youtube_url %>
  <%end%>
  <p><%= link_to image_tag(entry.image(:large)), entry.image.url %></p>
  <p><%= entry.contents %></p>
  <p><%= link_to "Delete", entry_path(entry), method: :delete %></p>

<% end %>
<%= link_to("New entry", new_entry_path) %>
</html>

app/views/entries/new.html.erb
<!doctype html>
<html>
  <head>
    <title>My Little Webapp: Coding Is Magic</title>
    <meta charset="UTF-8" />
    <link rel="stylesheet" href="https://rawgithub.com/krzysztofbialek/Rails-Girls-Warsaw-App/master/style.css" />
  </head>
  <body>
  	<img src="http://railsgirls.com/images/rg-warsaw.png" />
     <%=render "form"%>
<p><%= link_to("Back to all entries", entries_path) %></p>
  </body>
</html>

app/views/entries/show.html.erb
<!doctype html>
<html>
  <head>
    <title>My Little Webapp: Coding Is Magic</title>
    <meta charset="UTF-8" />
    <link rel="stylesheet" href="https://rawgithub.com/krzysztofbialek/Rails-Girls-Warsaw-App/master/style.css" />
  </head>
  <body>
  	<img src="http://railsgirls.com/images/rg-warsaw.png" />
  	<div>
  <h1>My favourite websites</h1>
  <h2><%= @entry.title %></h2>
  <p><%= @entry.date %></p>
  <% if @entry.youtube_url %>
  <%= youtube_embed @entry.youtube_url %>
  <%end%>
  <p><%= link_to image_tag(@entry.image.url(:large)), @entry.image.url %></p>
  <p><%= @entry.contents %></p>
  <p><%= link_to("Back to all entries", entries_path) %></p>
  <p><%= link_to("Edit this entry", edit_entry_path(@entry)) %></p>
  <p><%= link_to("Delete this entry", entry_path(@entry)) %></p>

  </div>
  <div>

  <%= form_for Comment.new do |f| %>
    <%= f.hidden_field :entry_id, value: @entry.id %>
    <p><%= f.label("entry_id") %></p>
    <p><%= f.label("nick") %></p>
    <p><%= f.text_field("nick") %></p>
    <p><%= f.label("contents") %></p>
    <p><%= f.text_area("contents") %></p>
    <p><%= f.submit %></p>
<% end %>
   <% for comment in @entry.comments %>
    <h3><%= comment.nick %></h3>
  <p><%= comment.contents %></p>
  <p><%= link_to("Delete this comment", comments_path(@comment)) %></p>
  <%end%>
  </div>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Diary</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/websites/_form.html.erb
<%= form_for(@website) do |form| %>
  <p><%= form.label("title") %></p>
  <p><%= form.text_field("title") %></p>
  <p><%= form.label("url") %></p>
  <p><%= form.text_area("url") %></p>
  <p><%= form.submit %></p>
<% end %>

app/views/websites/edit.html.erb
<!doctype html>
<html>
  <head>
    <title>My Little Webapp: Coding Is Magic</title>
    <meta charset="UTF-8" />
    <link rel="stylesheet" href="https://rawgithub.com/krzysztofbialek/Rails-Girls-Warsaw-App/master/style.css" />
  </head>
  <body>
  	<img src="http://railsgirls.com/images/rg-warsaw.png" />
   <%=render "form"%>
<p><%= link_to("Back to this website", website_path(@website)) %></p>
<p><%= link_to("Back to all websites", websites_path) %></p>
  </body>
</html>

app/views/websites/index.html.erb
<!doctype html>
<html>
  <head>
    <title>My Little Webapp: Coding Is Magic</title>
    <meta charset="UTF-8" />
    <link rel="stylesheet" href="https://rawgithub.com/krzysztofbialek/Rails-Girls-Warsaw-App/master/style.css" />
  </head>
  <body>
  	<div>
  <h1>My favourite websites</h1>
    <ul>
    </ul>
  </div>
  <img src="http://railsgirls.com/images/rg-warsaw.png" />
  </body>
         <% for website in @websites %>
  <h2><%= link_to(website.title, website_path(website)) %></h2>
  <p><%= website.title %></p>
  <p><%= website.url %></p>
  <p><%= link_to "Delete", website_path(website), method: :delete %></p>

<% end %>
<%= link_to("New website", new_website_path) %>
</html>

app/views/websites/new.html.erb
<!doctype html>
<html>
  <head>
    <title>My Little Webapp: Coding Is Magic</title>
    <meta charset="UTF-8" />
    <link rel="stylesheet" href="https://rawgithub.com/krzysztofbialek/Rails-Girls-Warsaw-App/master/style.css" />
  </head>
  <body>
  	<img src="http://railsgirls.com/images/rg-warsaw.png" />
     <%=render "form"%>
<p><%= link_to("Back to all websites", websites_path) %></p>
  </body>
</html>

app/views/websites/show.html.erb
<!doctype html>
<html>
  <head>
    <title>My Little Webapp: Coding Is Magic</title>
    <meta charset="UTF-8" />
    <link rel="stylesheet" href="https://rawgithub.com/krzysztofbialek/Rails-Girls-Warsaw-App/master/style.css" />
  </head>
  <body>
  	<img src="http://railsgirls.com/images/rg-warsaw.png" />
  	<div>
  <h1>My favourite websites</h1>
  <h2><%= @website.title %></h2>
  <p><%= @website.url %></p>
  <p><%= link_to image_tag(@entry.image.url(:large)), @entry.image.url %></p>
  <p><%= link_to("Back to all websites", websites_path) %></p>
  <p><%= link_to("Edit this website", edit_website_path(@website)) %></p>
  <p><%= link_to("Delete this website", entry_path(@website)) %></p>

  </div>
  <div>
  </div>

  </body>
</html>

app/views/welcome/_form.html.erb
<%= form_for(@entry) do |form| %>
  <p><%= form.label("title") %></p>
  <p><%= form.text_field("title") %></p>
  <p><%= form.label("contents") %></p>
  <p><%= form.text_area("contents") %></p>
  <p><%= form.submit %></p>
<% end %>

app/views/welcome/index.html.erb
<!doctype html>
<html>
  <head>
    <title>My Little Webapp: Coding Is Magic</title>
    <meta charset="UTF-8" />
    <link rel="stylesheet" href="https://rawgithub.com/krzysztofbialek/Rails-Girls-Warsaw-App/master/style.css" />
  </head>
  <body>
  	<div>
  <h1>My favourite websites</h1>
    <ul>
<% for website in @websites %>
  <li><a href="<%= website.url %>"><%= website.title %></a></li>
<% end %>
    </ul>
  </div>
  <img src="http://railsgirls.com/images/rg-warsaw.png" />

  <% for entry in @entries %>
    <h3><%= entry.title %></h3>
    <p><%= entry.date %></p>
    <p><%= entry.contents %></p>
    <p><%= link_to image_tag(entry.image.url(:large)), @entry.image.url %></p>
<%= link_to("Edit this entry", edit_entry_path(entry.id)) %>
<% end %>
 <%=render "form"%>
  </body>
</html>